add mens page layout
wecode-bootcamp-korea/31-1st-MUZIMAKZI-frontend pull request #12
Opened 2022-04-04 08:15 UTC by Jaehyuksssss

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-남성복 페이지 (Mens page) 부분의 레이아웃을 구현했습니다. 
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.mock Data와 map 함수를 이용하여 작은 리스트 부분을 구현했습니다.

2. 자주 쓰이는 UI 부분을 컴포넌트화 시켜 다시 재활용 할 수 있게 만들었습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-useState에 저장을 하고 페치프로토콜로 요청을 하여  map함수로 반복되는 부분을 구현하는 법을 익히게 되었습니다

<br />

## :: 기타 질문 및 특이 사항

2022-04-05 03:15 UTC, younuk23 requested changes
재혁님! 수정사항들 코멘트 달았습니다.
확인 및 반영해주세요!!

Conflict도 해결해주세요!

2022-04-05 03:15 UTC, yeonuk-hwang commented on src/Router.js
> +//임시된거라 push할땐 지워야함
ㅋㅋㅋㅋ 최종본에서는 삭제해주세요~!

2022-04-05 03:15 UTC, yeonuk-hwang commented on src/components/aside/Aside.js
> +      {CATEGOTY_LIST.map(category => {
```suggestion
      {CATEGOTY_LIST.map(({id, name, type}) => {
```

구조분해할당 해주면 훨씬 깔끔하겠네요! 함수 매개변수자리에서도 바로 구조분해할당 할 수 있습니다!

2022-04-05 03:15 UTC, yeonuk-hwang commented on src/components/aside/Aside.js
> +              {category.types.map(types => {
```suggestion
              {category.types.map(type => {
```

types 배열 안에 하나의 아이템들은 type이라고 부르는게 이치에 맞아보이네요

사소한 변수명부터시작해서 전체 코드의 가독성이 시작됩니다!

항상 오해없도록, 의미가 잘 드러나도록 이름 지어주세요!

2022-04-05 03:15 UTC, yeonuk-hwang commented on src/pages/Mens/Mens.js
> +    fetch('data/mensListData.json')
```suggestion
    fetch('/data/mensListData.json')
```

절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2022-04-05 03:15 UTC, yeonuk-hwang commented on src/pages/Mens/Mens.js
> +    <>
불필요한 div tag로 보입니다! 없어도 되겠네요

2022-04-05 03:15 UTC, younuk23 commented on src/styles/variables.scss
> +// @mixin flex
불필요한 주석 같네요!

2022-04-05 05:07 UTC, Jaehyuksssss commented on src/components/aside/Aside.js
> +      {CATEGOTY_LIST.map(category => {
aside 부분은 다른 팀원이 변경할 예정이여서 이 부분은 다른팀원이 수정 후 올리겠습니다!

2022-04-05 05:07 UTC, Jaehyuksssss commented on src/Router.js
> +//임시된거라 push할땐 지워야함
네~!!

2022-04-05 05:09 UTC, Jaehyuksssss commented on src/components/aside/Aside.js
> +              {category.types.map(types => {
이부분도 다른팀원이 수정 하겠다고 해서 다른 팀원이 수정 후 올리겠습니다

2022-04-05 05:11 UTC, Jaehyuksssss commented on src/pages/Mens/Mens.js
> +    fetch('data/mensListData.json')
수정했습니다!

2022-04-05 05:11 UTC, Jaehyuksssss commented on src/styles/variables.scss
> +// @mixin flex
수정했습니다!

2022-04-05 07:41 UTC, younuk23 commented
수정사항 반영이 안된 것 같네요 확인해주세요!
push하신 후에 항상 파일체인지 탭 확인하셔서 의도한대로 잘 수정이 되었는지 실수한 부분 없는지 꼼꼼히 확인하는 습관을 들이면 좋습니다!

그리고 라벨 잘 확인해주세요! 수정마쳤으면 수정요청라벨은 제거해주시면 됩니다.

그리고 추가기능구현중 라벨 붙어있는데 리뷰에 답글다신 내용으로는 작업이 완료된 것 같은데 상황이 어떻게 되나요?

2022-04-05 07:53 UTC, Jaehyuksssss commented
> 재혁님! 수정사항들 코멘트 달았습니다. 확인 및 반영해주세요!!
> 
> Conflict도 해결해주세요!

해결했습니다!

2022-04-06 01:52 UTC, younuk23 commented
재혁님 절대경로부분 수정했다고 말씀해주신 부분 수정이 안되어있습니다 확인 및 수정해주시고 라벨 수정해주세요!

2022-04-07 08:06 UTC, ghost commented on src/components/aside/Aside.js
> +const CATEGOTY_LIST = [
__[ESLint]__ 'CATEGOTY_LIST' is assigned a value but never used. ([view](https://sider.review/gh/repos/474886363/pulls/12#issue-6861617))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/474886363/pulls/12#issue-6861617) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-07 08:06 UTC, ghost commented on src/pages/Mens/Mens.js
> +                return (
__[ESLint]__ Replace `(⏎··················<MensList⏎····················key={id}⏎····················name={name}⏎····················thumbnail={thumbnail}⏎··················/>⏎················)` with `<MensList·key={id}·name={name}·thumbnail={thumbnail}·/>` ([view](https://sider.review/gh/repos/474886363/pulls/12#issue-6861618))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `prettier/prettier` | `error` | - |

References:
- <https://github.com/prettier/eslint-plugin-prettier#options>

You can [close this issue](https://sider.review/gh/repos/474886363/pulls/12#issue-6861618) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-07 08:06 UTC, ghost commented on src/pages/Mens/Mens.js
> +  }, []);
__[ESLint]__ React Hook useEffect has a missing dependency: 'params.id'. Either include it or remove the dependency array. ([view](https://sider.review/gh/repos/474886363/pulls/12#issue-6861619))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `react-hooks/exhaustive-deps` | `warn` | Yes |

References:
- <https://github.com/facebook/react/issues/14920>

You can [close this issue](https://sider.review/gh/repos/474886363/pulls/12#issue-6861619) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-07 08:41 UTC, yeonuk-hwang approved these changes

2022-04-07 08:41 UTC, merged