[31기 윤서영] list 페이지 UI 구현, 추가 기능
wecode-bootcamp-korea/31-1st-MUZIMAKZI-frontend pull request #14
Opened 2022-04-04 15:41 UTC by seo0yoon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 
1. sementic tag 사용
2. fetch() 함수를 사용해 API 호출
3. map() 함수로 component 재활용
4. list 페이지 ui 구현
5. Query Parameter를 사용해서 url 전달
6. Path Parameter로 상세페이지 연결

<br />

## :: 구현 사항 설명
1. sementic tag 사용
=> div tag 대신 nav나 h1~5 ul li  태그등을 사용하였습니다.

2. fetch() 함수를 사용해 API 호출
=> fetch 함수를 활용하여 백엔드와 데이터통신을 하던 중,
console.log(데이터이름.message)로 찍어보면 콘솔에 정상적으로 데이터가 받아졌지만,
state에 저장하면 자꾸 [] 빈배열만 찍히는 이상한 현상이 나타났습니다. 
콘솔을 다시 확인하니 받은 데이터가 배열안에 객체가 들어있는 것을 확인하고,
저장이 안되는 state에 {setItemInfo(data.message)} 중괄호를 하여 데이터 통신을 해결하였습니다.

3. map() 함수로 component 재활용
=> 스프레드 연산자를 사용할 수 있게 되었고,  nav박스의 리스트목록을 map 함수로 돌렸는데 
각각의 list마다 className이 다르고 속성도 달랐습니다. 어떻게 style속성을 줄까
고민하다가, 상수 데이터에  className: 'selectList' 을 추가하였고, 정상적으로 style 속성을 주었습니다.

4. Query Parameter를 사용해서 url 전달
=> 버튼을 클릭했을때 데이터를 가져올 수 있도록 조건을 걸어 삼항연산자를 활용하였고, 
버튼이 눌리면 bold가 될 수 있도록 onClick 이벤트를 적용하였습니다.
useLocation을 활용하여 search값을 가져오고 데이터를 `템플릿 리터럴` 을 활용하여 적용하였습니다.

5. Path Parameter로 상세페이지 연결
=> list 페이지 안에 목록들을 상세페이지로 연결 시켜주기 위하여, 패스 파라미터를 사용하였습니다.
라우터 경로에  :id 값을 붙인 후,  navigate를 연결해주었습니다.

<br />

## :: 성장 포인트

1. sementic tag 사용
=> 반복적인 div tag가 아닌 sementic tag를 사용하며 유지 보수와 검색엔진 최적화를 신경 쓰게 되었습니다.
strong tag와 b tag의 차이점을 알게 되었고, 단순히 bold 값을 주고 싶다면 className으로
font-weight 속성을 주는 것이 적합하고, 웹 접근성까지 생각한다면 strong tag를 쓰는 것이
조금 더 낫다는 생각도 들었습니다.

2. fetch() 함수를 사용해 API 호출
=> 백엔드와 소통하여 API를 호출하는 방법을 배웠고, 데이터 통신은 처음부터 정확한 KEY 값을
맞춘 후, 진행해야 좋다는 것을 알게 되었습니다.

3. list 페이지 ui 구현
=> scss 속성에 순서를 정해놓음으로 특정 속성을 쉽게 찾을 수 있게 되었습니다.
&:nth-child(n) 같은 가상 요소 선택자를 활용하여, n번째 요소마다 스타일 속성을 주는 방법을 배웠습니다.

4. Query Parameter를 사용해서 url 전달
=> 삼항연산자와 템플릿 리터럴을 사용하는 방법을 알게 되었고, [location.search]를 의존성 배열에 넣어서 
location.search가 실행될 때만 lender되도록 만드는 방법을 배웠습니다.

6. Path Parameter로 상세페이지 연결
=> 클릭했을때 상세페이지로 이동하도록 onclick 이벤트를 넣었고, 
템플릿 리터럴을 활용하여 숫자를 보관하는 방법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-04-05 05:18 UTC, younuk23 requested changes
고생하셨습니다 서영님 리뷰 확인 및 반영하면서 작업 진행해주세요!

2022-04-05 05:18 UTC, younuk23 commented on src/pages/Labo/Labo.js
> +  return <div>무지막지</div>;
이부분 파일이 지워졌는데 의도한 변경인가요? 아니라면, 다시 롤백해주세요
만약 아직 마스터에 있는 내용들이 반영 안된거라면, 마스터있는 내용 머지한번 해주시면 될 것 같습니다!

의도적으로 한거라면 코멘트로 남겨주세요!

2022-04-05 05:18 UTC, younuk23 commented on src/pages/List/List.js
> +  // }, []);
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-04-05 05:18 UTC, younuk23 commented on src/pages/List/List.js
> +    fetch('http://localhost:3000/data/MockData.json')
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2022-04-05 05:18 UTC, younuk23 commented on src/pages/List/List.js
> +          ))}
이름이 좀 더 명확하면 좋을 것 같네요!

Info등의 접미사는 안붙이는게 좋습니다!
Item vs ItmeInfo 로 생각했을 때 어떤 부분이 차이가 있는지 Info라는 단어들로는 명확히 알기 힘들겠죠??

상품에 대한 정보라면 그리고 Item이라는 단어도 좀 불분명한것 같아서 상품에 대한 정보라면 products정도로 표현하는게 좋겠네요!

```suggestion
          {products.map(product => (
            <ItemList key={product.id} {...product} />
          ))}
```

그러면 위와 같이 좀 더 알아보기 쉬운 형태가 되겠네요!!
ItemList라는 컴포넌트 명도 실질적으로 리스트가 아닌 단일 아이템을 표현하는 컴포넌트 같으니까 수정해주는게 좋겠네요!

2022-04-05 05:18 UTC, younuk23 commented on src/pages/List/SelectBoxComponents/selectBox.js
> +        ))}
상수데이터 활용 👍

다만 위에서 드린 코멘트와 마찬가지로 DATA, INFO등의 접미사는 안붙는게 오히려 더 낫습니다.

변수명만 수정해주세요!

2022-04-05 07:18 UTC, seo0yoon commented on src/pages/Labo/Labo.js
> +  return <div>무지막지</div>;
네! 연욱님 의도한건 아니고 실수로 지운것 같습니다! 다시 되돌리겠습니다

2022-04-05 07:26 UTC, seo0yoon commented on src/pages/List/List.js
> +  // }, []);
네! 연욱님~

2022-04-05 07:26 UTC, seo0yoon commented on src/pages/List/List.js
> +    fetch('http://localhost:3000/data/MockData.json')
네 생략하겠씁니다~!

2022-04-05 07:38 UTC, seo0yoon commented on src/pages/List/List.js
> +          ))}
네 감사합니다! 수정하였습니다~

2022-04-05 07:41 UTC, seo0yoon commented on src/pages/List/SelectBoxComponents/selectBox.js
> +        ))}
네 연욱님 수정하였습니다~ 감사합니다 ㅎㅎ

2022-04-07 02:24 UTC, seo0yoon commented on src/pages/List/List.js
> +  }, [location.search]);
vs코드상에는 eslint 경고가 발생하지않는데 사이더에는 걸려있습니다! 어떻게 할까요 연욱님?!ㅜㅜ

2022-04-07 04:45 UTC, younuk23 requested changes
컨플릭 해결하는 과정에서 잘못된 코드가 남아있는 것 같네요!! 해결해주세요!!

2022-04-07 05:58 UTC, seo0yoon commented
> 컨플릭 해결하는 과정에서 잘못된 코드가 남아있는 것 같네요!! 해결해주세요!!
네 연욱님~! 해결하고 푸시하였습니다!

2022-04-07 07:05 UTC, younuk23 approved these changes
LGTM

2022-04-07 07:05 UTC, younuk23 commented on src/pages/List/List.js
> +  }, [location.search]);
이부분은 일단 넘어갈게요!! 왜 발생하는지 및 어떻게 해결해야하는지에 대해서는 아래 코멘트 참고해주시면 될 것 같습니다!

useEffect상에서 dependency array를 잘 설정하는건 중요합니다!!
관련되서는 클로저, primitive type, reference type등 다양한 개념의 이해가 필요합니다.
useEffect에 관련되서 아래의 잘 정리된 아티클 하나 공유드립니다!
당장 이해안되더라도 나중에 찬찬히 읽어보고 찾아보시면 좋을것 같습니다!
[useEffect 완벽 가이드](https://www.rinae.dev/posts/a-complete-guide-to-useeffect-ko)

2022-04-07 07:05 UTC, merged