Feature/sign
wecode-bootcamp-korea/31-1st-MUZIMAKZI-frontend pull request #7
Opened 2022-03-31 04:05 UTC by Moonhyeseong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 이메일, 비밀번호 입력창을 사용한 로그인 기능 구현 
- 이름, 전화번호, 이메일 ,비밀번호 입력창을 사용한 로그인 기능 구현
- 탭 클릭을 통한 로그인, 회원가입 창으로의 전환

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-04 02:44 UTC, younuk23 commented
혜성님 추가기능구현중이지만, 리뷰 요청 및 피드백 받으시길 원하는 경우라면
- PR 본문 작성
- 리뷰요청 라벨 부착
위 사항들 진행해주세요~!

2022-04-04 06:40 UTC, younuk23 requested changes
고생하셨습니다 혜성님, 코드에서 많은 고민이랑 시도의 흔적이 보여서 좋네요!! 

리뷰 확인 및 반영해주세요!!

2022-04-04 06:40 UTC, younuk23 commented on src/components/nav/Nav.js
> +      {signModal ? <LoginSignup handleLoginModal={handleLoginModal} /> : null}
```suggestion
      {signModal && <LoginSignup handleLoginModal={handleLoginModal} />}
```
true일 경우만 처리한다면, 삼항연산자보다는 && 연산자가 더 간결하게 표현 가능합니다!

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/LoginSignup.js
> +  const checkSignUpInput = () => {
api주소는 `config.js` 에서 관리하는 것으로 수정해주세요

API는 `config.js` 파일에서 일괄적으로 관리하면서 import, export 를 통해 사용하는 식으로 관리하는 것이 좋습니다. 그렇지 않을 경우, 백엔드 서버 IP 가 변경되면 fetch 함수를 일일이 찾아서 API 를 직접 수정해 주어야 하기 때문입니다.

아래는 config.js에서 API주소를 관리하는 하나의 예시입니다. 참고하셔서 팀원들과 논의 후 생각하신 방식으로 자유롭게 적용해주세요

```jsx
// src/config.js
const BASE_URL = 'http://10.58.5.151:8000'
const API = {
  product:`${BASE_URL}/products`,
  list:`${BASE_URL}/list`
}

// 사용하는 컴포넌트
import { API } from '../../../config.js';

...

fetch(`${API}/5`).then(...).then(...);
```

위의 경우, 백엔드 IP 가 바뀔 때 `config.js` 에서 IP 만 바꾸어주면 모든 API 가 새로운 IP 에 따라서 변경됩니다. 그렇기 때문에 일일이 fetch 함수를 찾아 API 를 수정해줄 필요가 없습니다.

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/LoginSignup.js
> +        phone_number: signUpInput.phoneNumber,
signUpInput 부분 구조분해할당 위에서 한번 해주면 반복적으로 작성 안해도 되겠네요!

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/LoginSignup.js
> +        phone_number: signUpInput.phoneNumber,
signUpInput 부분 구조분해할당 위에서 한번 해주면 반복적으로 작성 안해도 되겠네요!

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/components/Form.js
> +                handleSignUpValid={signUpValidator[input.type]}
👍 object 써서 유효성검사 함수 매핑한것 너무 좋네요

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/components/Input.js
> +  const valid = value => {
함수 이름이 조금 더 명확하면 좋겠네요!

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/components/Input.js
> +  });
```suggestion
  useEffect(() => {
    valid(value);
  }, [value]);
```

value가 바뀔 때에만 유효성검사를 할 필요가 있을 것 같으니, value를 의존성배열에 명확히 넣어주는게 좋아보이네요! 안그러면 다른 props이나 state가 바껴서 re-render될 때도 매번 불필요하게 valid함수를 호출합니다!


그리고 가장 좋은 방법은 굳이 valid를 state로 안하고 그냥 일반 변수로 선언해도 하는게 좋아보이네요!

다른 props으로부터 계산 가능한 값은 굳이 다시 state로 만들필요가 없습니다.

[공식문서 React로 사고하기](https://ko.reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state) 를 보시면 어떤 값들이 state가 되어야하는지에 대해 적혀있습니다.

> 각각 살펴보고 어떤 게 state가 되어야 하는 지 살펴봅시다. 이는 각 데이터에 대해 아래의 세 가지 질문을 통해 결정할 수 있습니다
> 

> 1. 부모로부터 props를 통해 전달됩니까? 그러면 확실히 state가 아닙니다.
> 

> 2. 시간이 지나도 변하지 않나요? 그러면 확실히 state가 아닙니다.
> 

> 3. 컴포넌트 안의 다른 state나 props를 가지고 계산 가능한가요? 그렇다면 state가 아닙니다.
>

2022-04-04 06:40 UTC, younuk23 commented on src/pages/LoginSignup/components/Input.js
> +        {name === 'signIn' ? null : isValid ? <ValidCheck /> : <InValidCheck />}
Input을 쓰는 부분에서 공통적으로 name이 singup인지 signin인지 따라서 validation 문구를 표출할지 말지를 검사하는 부분이 계속 들어가는데, 이렇게 하는것 보다 props로 validation UI를 표시 할지 말지를 처리하는게 좋아보입니다.

아니면, Input 컴포넌트에서 validation 검사를 하는 함수를 받는 것이 아니라, valid한지 아닌지의 true, false값만 받는식으로 설계하는게 좋다고 생각됩니다.

이렇게되면 true or false로 props 값이 전달됬다면, 해당하는 텍스트를 표시하고,
만약 값이 전달되지 않았다면(undefined) 어떤 표시도 하지 않는식으로 깔끔하게 표현할 수 있어보입니다. 한번 시도해보세요!

2022-04-04 08:19 UTC, Moonhyeseong commented on src/components/nav/Nav.js
> +      {signModal ? <LoginSignup handleLoginModal={handleLoginModal} /> : null}
리뷰 반영하여 수정했습니다!

2022-04-04 08:31 UTC, Moonhyeseong commented on src/pages/LoginSignup/components/Input.js
> +  });
일반 변수로 선언하는 방법으로 변경했습니다. 불필요한 Hook을 두가지나 줄일수 있었어요

2022-04-04 08:40 UTC, Moonhyeseong commented on src/pages/LoginSignup/components/Input.js
> +  const valid = value => {
변수로 변경하니 함수를 사용하지 않게 되었습니다.

2022-04-04 08:41 UTC, Moonhyeseong commented on src/pages/LoginSignup/components/Form.js
> +                handleSignUpValid={signUpValidator[input.type]}
감사합니다!

2022-04-04 08:48 UTC, Moonhyeseong commented on src/pages/LoginSignup/LoginSignup.js
> +        phone_number: signUpInput.phoneNumber,
수정했습니다!

2022-04-04 08:48 UTC, Moonhyeseong commented on src/pages/LoginSignup/LoginSignup.js
> +        phone_number: signUpInput.phoneNumber,
수정했습니다!

2022-04-04 10:03 UTC, Moonhyeseong commented on src/pages/LoginSignup/components/Input.js
> +        {name === 'signIn' ? null : isValid ? <ValidCheck /> : <InValidCheck />}
리뷰사항 최대한 반영해 수정했습니다.

2022-04-05 02:37 UTC, younuk23 approved these changes
reset.scss부분은 팀원들과 합의하에 추가된거겠죠?

수정사항 코멘트 하나 남겼는데 다음 작업할때 참고해서 반영해주세요! 
머지하겠습니다! LGTM 👍

2022-04-05 02:37 UTC, younuk23 commented on src/pages/LoginSignup/components/Input.js
> +        {isLogin ? null : isValid ? <ValidCheck /> : <InValidCheck />}
```suggestion
        {isValid !== undefined && isValid ? <ValidCheck /> : <InValidCheck />}
```

isValid값을 Singup일때만 전달받는다면, 위와 같이 처리 가능해보이네요
그러면 isLogin이란 값을 받을 필요가 없어지고요!

참고해서 반영해보세요!

2022-04-05 02:37 UTC, merged

2022-04-05 02:39 UTC, younuk23 commented
그리고, 구현사항 설명에 로그인부분 상세하게 계획 세워서 설명하신것 너무 좋네요!

앞으로도 작업 전에 미리 저런식으로 구상하고 작업하시면 훨씬 더 빠르게 느실 수 있을거에요!